cloud_srt_host: srt://your-cloud-server:9000
low_resolution: 640x360
motion_cooldown: 10
motion_high_fps: 25
motion_low_fps: 1
motion_min_area: 500
motion_sensitivity: 25
motion_zones: []
normal_resolution: 1280x720
srt_passphrase: your-secure-passphrase-here
streams:
- enabled: true
  id: cam1
  name: backyard
  rtsp_url: rtsp://orinnano:orinnano@192.168.1.102:554/stream1
- enabled: true
  id: cam2
  name: porch
  rtsp_url: rtsp://orinnano:orinnano@192.168.1.103:554/stream1
telegram_bot_token: ''
telegram_chat_id: ''
upload_speed_threshold_mbps: 2
web_host: 0.0.0.0
web_port: 5000
