cloud_password: tapwaysuperadmin
cloud_upload_enabled: true
cloud_upload_url: http://101.47.153.138:8081
cloud_username: tapway
motion_cooldown: 3
motion_min_area: 5000
motion_sensitivity: 50
motion_zones: []
streams:
- chunk_duration: 5
  chunk_fps: 1
  chunking_enabled: true
  enabled: true
  id: cam1
  name: Camera 192.168.68.115
  rtsp_url: rtsp://orinnano:orinnano@192.168.68.115:554/stream1
  streaming_enabled: true
